name: CI Unit Tests

on: [push]

jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: compile and run test suite
      run:  |
        gcc test/testSafeString.c -o tests
        ./tests

        
