name: C/C++ CI

on: [push]

jobs:
  build-and-run-tests:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: compile tests
      run:  gcc test/testSafeString.c -o tests
            ./test/tests

        
