name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: compile tests
      run: gcc -o test/testSafeString.c -o tests
  
  run:
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: run tests
        run: ./test/tests
